### ISSUE TITLE
Can i use it for my purpose? 

### ISSUE THREAD

**Issue by dsuinfo** [sdzshn3/OneSignalAPI#1]
Hello i am new on android development. I was searching ad free onesignal app and found it so can i use this source code to modify with my name etc. And publish on playstore without ad free of cost. Because ihave developed one app and client have to send notifications but right now they have to goto onesignal site and login and send notification. If you permit me to use than i am will be very thankful. And sorry posted in issue because i am new on github

**Comment by sdzshn3** [comment]
Hello @dsuinfo , are you going to use the code for integrating notification sending feature in admin panel kind of app or, will you just duplicate same as my app and publish in play store?

**Comment by dsuinfo** [comment]
will duplicate this code remove your name and put my and publish in
playstore. because i want this app to give my client to send push
notifications via app. right now they are using panel to do this. Thanks

**Comment by sdzshn3** [comment]
Then just let your client use my app. What's gonna change when you just duplicate the app.

**Comment by dsuinfo** [comment]
i will use my branding simply if you allow.. thanks

**Comment by sdzshn3** [comment]
Sorry but I already told in readme that don't reuse, modify or publish
source code. So, I won't agree with that.

**Comment by dsuinfo** [comment]
okay thanks for inform
